/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2023-06-11 08:25:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1679567181629L));
    _jspx_dependants.put("jar:file:/E:/A_TeachingMaterial/05_JSP_Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourmine/WEB-INF/lib/spring-webmvc-5.3.6.jar!/META-INF/spring.tld", Long.valueOf(1618279800000L));
    _jspx_dependants.put("jar:file:/E:/A_TeachingMaterial/05_JSP_Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourmine/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.6.jar", Long.valueOf(1680657633229L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\n");
      out.write("#scrollArea{\r\n");
      out.write("\theight: 360px;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("  \tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("#scrollArea::-webkit-scrollbar {\r\n");
      out.write("  display: none; /* Chrome, Safari, and Opera */\r\n");
      out.write("}\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div id=\"mytask-layout\" class=\"theme-indigo\">\r\n");
      out.write("\r\n");
      out.write("    <!-- main body area -->\r\n");
      out.write("    <div class=\"main px-lg-4 px-md-4\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Body: Body -->\r\n");
      out.write("        <div class=\"body d-flex py-3\">\r\n");
      out.write("            <div class=\"p-4 m-4\">\r\n");
      out.write("                <div class=\"row clearfix g-3\">\r\n");
      out.write("                    <div class=\"col-xl-8 col-lg-12 col-md-12 flex-column\">\r\n");
      out.write("                        <div class=\"row g-3\">\r\n");
      out.write("                            <div class=\"col-md-12 mb-2\">\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                    <div class=\"card-header py-3 d-flex justify-content-between bg-transparent border-bottom-0 mt-2\">\r\n");
      out.write("                                        <h6 class=\"mb-0 fw-bold \">접속자 변동 내역</h6>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"ac-line-transparent\" id=\"apex-emplyoeeAnalytics11\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("<!-- 여기원형 -->\t\t\t<div class=\"row g-3 mb-3 row-deck\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 col-lg-6\">\r\n");
      out.write("\t\t                        <div class=\"card\">\r\n");
      out.write("\t\t                            <div class=\"card-body\">\r\n");
      out.write("\t\t                               <h6 class=\"mb-0 fw-bold\">매출</h6>\r\n");
      out.write("\t\t                                <div class=\"d-flex justify-content-end text-center\">\r\n");
      out.write("\t\t                                    <div class=\"p-2 ms-4\">\r\n");
      out.write("\t\t                                        <h6 class=\"mb-0 fw-bold\" id=\"salesSUM\"></h6>\r\n");
      out.write("\t\t                                        <small class=\"text-muted\">수입(원)</small>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                </div>\r\n");
      out.write("\t\t                                <div class=\"\" id=\"incomeanalytics11\"></div>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\r\n");
      out.write("\t\t                    \r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                    <div class=\"card-header py-3 d-flex justify-content-between bg-transparent border-bottom-0\">\r\n");
      out.write("                                        <h6 class=\"mb-0 fw-bold \">회사 소속 회원</h6>\r\n");
      out.write("                                        <div class=\"p-2 ms-4 text-center\">\r\n");
      out.write("\t\t                                    <h4 class=\"mb-0 fw-bold \" id=\"joinCompanyMemberCNT\"></h4>\r\n");
      out.write("\t                                        <small class=\"text-muted\">명</small>\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"\" id=\"apex-MainCategories11\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-lg-12 col-md-12\">\r\n");
      out.write("                        <div class=\"row g-3 row-deck\">\r\n");
      out.write("                            <div class=\"col-md-6 col-lg-6 col-xl-12\">\r\n");
      out.write("                                <div class=\"card bg-primary\">\r\n");
      out.write("                                    <div class=\"card-body row\">\r\n");
      out.write("                                        <div class=\"col\">\r\n");
      out.write("                                            <span class=\"avatar lg bg-white rounded-circle text-center d-flex align-items-center justify-content-center\"><i class=\"icofont-file-text fs-5\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- 회원수 표시 -->\r\n");
      out.write("                                            <h1 class=\"mt-3 mb-0 fw-bold text-white\" id=\"selMemCNT\"></h1>\r\n");
      out.write("                                            <span class=\"text-white\">회원</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col\">\r\n");
      out.write("                                            <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/task-view.svg\" alt=\"interview\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 col-lg-6 col-xl-12  flex-column\">\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center flex-fill\">\r\n");
      out.write("                                            <span class=\"avatar lg light-success-bg rounded-circle text-center d-flex align-items-center justify-content-center\"><i class=\"icofont-holding-hands fs-5\"></i></span>\r\n");
      out.write("                                            <div class=\"d-flex flex-column ps-3 flex-fill\">\r\n");
      out.write("                                                <h6 class=\"fw-bold mb-0 fs-4\" id=\"selSubMemCNT\"></h6>\r\n");
      out.write("                                                <span class=\"text-muted\">구독회사</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <i class=\"icofont-chart-line fs-3 text-muted\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-12 col-lg-12 col-xl-12\">\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-header py-3 d-flex justify-content-between bg-transparent border-bottom-0\">\r\n");
      out.write("                                    <h6 class=\"mb-0 fw-bold \">구독마감 임박 회원</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\" id=\"scrollArea\">\r\n");
      out.write("                                    <div class=\"flex-grow-1\" id=\"subEndCloseComListArea\">\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <div class=\"card light-danger-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t                        <div class=\"card mb-3\">\r\n");
      out.write("\t\t                            <div class=\"card-header d-flex justify-content-between align-items-center bg-transparent border-bottom-0\">\r\n");
      out.write("\t\t                                <h6 class=\"m-0 fw-bold\">구독현황</h6>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                            <div class=\"card-body\">\r\n");
      out.write("\t\t                                <div id=\"apex-chart-line-column11\"></div>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!-- Row End -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("const selMemCNT = $(\"#selMemCNT\");\r\n");
      out.write("const selSubMemCNT = $(\"#selSubMemCNT\");\r\n");
      out.write("const subEndCloseComListArea = $(\"#subEndCloseComListArea\");\r\n");
      out.write("const companyMemberCNT = $(\"#joinCompanyMemberCNT\");\r\n");
      out.write("const salesSUM = $(\"#salesSUM\");\r\n");
      out.write("\r\n");
      out.write("let selMemChartNum = '';\r\n");
      out.write("const getMemCNT=()=>{\r\n");
      out.write("\tconsole.log(\"getMemCNT\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  type:\"get\",\r\n");
      out.write("\t\t  url:\"/ourmine/index/adminIndex/getMemCNT\",\r\n");
      out.write("\r\n");
      out.write("\t\t  dataType:\"json\",\r\n");
      out.write("\t\t  async:false,\r\n");
      out.write("\t\t  success:function(resp){\r\n");
      out.write("\t\t      console.log(\"getMemCNT결과:{}\",resp);  // 요기 코드가 길어지면  별도 함수로 처리/ 그래야 가독성이 유지됨\r\n");
      out.write("\t\t      selMemCNT.text(resp);\r\n");
      out.write("\t\t      selMemChartNum = resp;\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  error: function (request, status, error) {\r\n");
      out.write("\t\t      console.log(\"code: \" + request.status)\r\n");
      out.write("\t\t      console.log(\"message: \" + request.responseText)\r\n");
      out.write("\t\t      console.log(\"error: \" + error);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("const getSubMemCNT=()=>{\r\n");
      out.write("\tconsole.log(\"getSubMemCNT\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  type:\"get\",\r\n");
      out.write("\t\t  url:\"/ourmine/index/adminIndex/selectSubscribeCNT\",\r\n");
      out.write("\r\n");
      out.write("\t\t  dataType:\"json\",\r\n");
      out.write("\t\t  success:function(resp){\r\n");
      out.write("\t\t      console.log(\"selectSubscribeCNT결과:{}\",resp);  \r\n");
      out.write("\t\t      selSubMemCNT.text(resp);\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  error: function (request, status, error) {\r\n");
      out.write("\t\t      console.log(\"code: \" + request.status)\r\n");
      out.write("\t\t      console.log(\"message: \" + request.responseText)\r\n");
      out.write("\t\t      console.log(\"error: \" + error);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("const selectSubEndCloseComList=()=>{\r\n");
      out.write("\tconsole.log(\"selectSubEndCloseComList\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  type:\"get\",\r\n");
      out.write("\t\t  url:\"/ourmine/index/adminIndex/selectSubEndCloseComList\",\r\n");
      out.write("\r\n");
      out.write("\t\t  dataType:\"json\",\r\n");
      out.write("\t\t  success:function(resp){\r\n");
      out.write("\t\t      console.log(\"selectSubEndCloseComList결과:{}\",resp);\r\n");
      out.write("\r\n");
      out.write("\t\t      for(let i=0; i< resp.length; i++){\r\n");
      out.write("\t\t\t      subEndCloseComListArea.append(\r\n");
      out.write("\t\t\t\t    \t`\r\n");
      out.write("\t\t                  <div class=\"py-2 d-flex align-items-center border-bottom flex-wrap\">\r\n");
      out.write("\t\t                      <div class=\"d-flex align-items-center flex-fill\">\r\n");
      out.write("\t\t                          <img class=\"avatar lg rounded-circle img-thumbnail\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/lg/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("\t\t                          <div class=\"d-flex flex-column ps-3\">\r\n");
      out.write("\t\t                              <h6 class=\"fw-bold mb-0 small-14\">${resp[i].memberName}</h6>\r\n");
      out.write("\t\t                              <span class=\"text-muted\">${resp[i].companyName}</span>\r\n");
      out.write("\t\t                          </div>\r\n");
      out.write("\t\t                      </div>\r\n");
      out.write("\t\t                      <div class=\"time-block text-truncate\">\r\n");
      out.write("\t\t                          <i class=\"icofont-clock-time\"></i>${resp[i].subscribeEndDate}\r\n");
      out.write("\t\t                      </div>\r\n");
      out.write("\t\t                  </div>\r\n");
      out.write("\t\t\t\t    \t`\t\t\t      \r\n");
      out.write("\t\t  \t\t\t)\r\n");
      out.write("\t\t     \t }\r\n");
      out.write("\t\t      },\r\n");
      out.write("\t\t  error: function (request, status, error) {\r\n");
      out.write("\t\t      console.log(\"code: \" + request.status)\r\n");
      out.write("\t\t      console.log(\"message: \" + request.responseText)\r\n");
      out.write("\t\t      console.log(\"error: \" + error);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("let comMemChartNum ='';\r\n");
      out.write("const joinCompanyMemberCNT=()=>{\r\n");
      out.write("\tconsole.log(\"joinCompanyMemberCNT\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  type:\"get\",\r\n");
      out.write("\t\t  url:\"/ourmine/index/adminIndex/joinCompanyMemberCNT\",\r\n");
      out.write("\t\t  async:false,\r\n");
      out.write("\t\t  dataType:\"json\",\r\n");
      out.write("\t\t  success:function(resp){\r\n");
      out.write("\t\t      console.log(\"joinCompanyMemberCNT결과:{}\",resp);  \r\n");
      out.write("\t\t      companyMemberCNT.text(resp);\r\n");
      out.write("\t\t      comMemChartNum = resp;\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  error: function (request, status, error) {\r\n");
      out.write("\t\t      console.log(\"code: \" + request.status)\r\n");
      out.write("\t\t      console.log(\"message: \" + request.responseText)\r\n");
      out.write("\t\t      console.log(\"error: \" + error);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("const selectSalesSUM=()=>{\r\n");
      out.write("\tconsole.log(\"selectSalesSUM\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  type:\"get\",\r\n");
      out.write("\t\t  url:\"/ourmine/index/adminIndex/selectSalesSUM\",\r\n");
      out.write("\r\n");
      out.write("\t\t  dataType:\"json\",\r\n");
      out.write("\t\t  success:function(resp){\r\n");
      out.write("\t\t      console.log(\"selectSalesSUM결과:{}\",resp);  \r\n");
      out.write("\t\t      let formattedResp = resp.toLocaleString(undefined, { maximumFractionDigits: 0 });\r\n");
      out.write("\t\t      salesSUM.text(formattedResp);\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  error: function (request, status, error) {\r\n");
      out.write("\t\t      console.log(\"code: \" + request.status)\r\n");
      out.write("\t\t      console.log(\"message: \" + request.responseText)\r\n");
      out.write("\t\t      console.log(\"error: \" + error);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("let salesItemCNT ='';\r\n");
      out.write("const selectSalesItemCNT=()=>{\r\n");
      out.write("\tconsole.log(\"selectSalesItemCNT\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  type:\"get\",\r\n");
      out.write("\t\t  url:\"/ourmine/index/adminIndex/selectSalesItemCNT\",\r\n");
      out.write("\t\t  dataType:\"json\",\r\n");
      out.write("\t\t  async:false,\r\n");
      out.write("\t\t  success:function(resp){\r\n");
      out.write("\t\t      console.log(\"selectSalesItemCNT결과:{}\",resp);  \r\n");
      out.write("\t\t      salesItemCNT=resp;\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  error: function (request, status, error) {\r\n");
      out.write("\t\t      console.log(\"code: \" + request.status)\r\n");
      out.write("\t\t      console.log(\"message: \" + request.responseText)\r\n");
      out.write("\t\t      console.log(\"error: \" + error);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("let subscribeJANUARY='';\r\n");
      out.write("let subscribeFEBRUARY='';\r\n");
      out.write("let subscribeMARCH='';\r\n");
      out.write("let subscribeAPRIL='';\r\n");
      out.write("let subscribeMAY='';\r\n");
      out.write("let subscribeJUNE='';\r\n");
      out.write("let subscribeJULY='';\r\n");
      out.write("let subscribeAUGUST='';\r\n");
      out.write("let subscribeSEPTEMBER='';\r\n");
      out.write("let subscribeOCTOBER='';\r\n");
      out.write("let subscribeNOVEMBER='';\r\n");
      out.write("let subscribeDECEMBER='';\r\n");
      out.write("\r\n");
      out.write("const selectMonthlySubscribeCNT=()=>{\r\n");
      out.write("\tconsole.log(\"selectMonthlySubscribeCNT\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  type:\"get\",\r\n");
      out.write("\t\t  url:\"/ourmine/index/adminIndex/selectMonthlySubscribeCNT\",\r\n");
      out.write("\t\t  dataType:\"json\",\r\n");
      out.write("\t\t  async:false,\r\n");
      out.write("\t\t  success:function(resp){\r\n");
      out.write("\t\t      console.log(\"selectMonthlySubscribeCNT결과:{}\",resp);\r\n");
      out.write("\t\t      subscribeJANUARY = resp[0][\"JANUARY\"];\r\n");
      out.write("\t\t      subscribeFEBRUARY = resp[0][\"FEBRUARY\"];\r\n");
      out.write("\t\t      subscribeMARCH = resp[0][\"MARCH\"];\r\n");
      out.write("\t\t      subscribeAPRIL = resp[0][\"APRIL\"];\r\n");
      out.write("\t\t      subscribeMAY = resp[0][\"MAY\"];\r\n");
      out.write("\t\t      subscribeJUNE = resp[0][\"JUNE\"];\r\n");
      out.write("\t\t      subscribeJULY = resp[0][\"JULY\"];\r\n");
      out.write("\t\t      subscribeAUGUST = resp[0][\"AUGUST\"];\r\n");
      out.write("\t\t      subscribeSEPTEMBER = resp[0][\"SEPTEMBER\"];\r\n");
      out.write("\t\t      subscribeOCTOBER = resp[0][\"OCTOBER\"];\r\n");
      out.write("\t\t      subscribeNOVEMBER = resp[0][\"NOVEMBER\"];\r\n");
      out.write("\t\t      subscribeDECEMBER = resp[0][\"DECEMBER\"];\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  error: function (request, status, error) {\r\n");
      out.write("\t\t      console.log(\"code: \" + request.status)\r\n");
      out.write("\t\t      console.log(\"message: \" + request.responseText)\r\n");
      out.write("\t\t      console.log(\"error: \" + error);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("let JoinMemberJANUARY='';\r\n");
      out.write("let JoinMemberFEBRUARY='';\r\n");
      out.write("let JoinMemberMARCH='';\r\n");
      out.write("let JoinMemberAPRIL='';\r\n");
      out.write("let JoinMemberMAY='';\r\n");
      out.write("let joinMemberJUNE='';\r\n");
      out.write("let joinMemberJULY='';\r\n");
      out.write("let joinMemberAUGUST='';\r\n");
      out.write("let joinMemberSEPTEMBER='';\r\n");
      out.write("let joinMemberOCTOBER='';\r\n");
      out.write("let joinMemberNOVEMBER='';\r\n");
      out.write("let joinMemberDECEMBER='';\r\n");
      out.write("const selectMonthlyJoinMemberCNT=()=>{\r\n");
      out.write("\tconsole.log(\"selectMonthlyJoinMemberCNT\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  type:\"get\",\r\n");
      out.write("\t\t  url:\"/ourmine/index/adminIndex/selectMonthlyJoinMemberCNT\",\r\n");
      out.write("\t\t  dataType:\"json\",\r\n");
      out.write("\t\t  async:false,\r\n");
      out.write("\t\t  success:function(resp){\r\n");
      out.write("\t\t      console.log(\"selectMonthlyJoinMemberCNT결과:{}\",resp);  \r\n");
      out.write("\t\t      JoinMemberJANUARY = resp[0][\"JANUARY\"];\r\n");
      out.write("\t\t      JoinMemberFEBRUARY = resp[0][\"FEBRUARY\"];\r\n");
      out.write("\t\t      JoinMemberMARCH = resp[0][\"MARCH\"];\r\n");
      out.write("\t\t      JoinMemberAPRIL = resp[0][\"APRIL\"];\r\n");
      out.write("\t\t      JoinMemberMAY = resp[0][\"MAY\"];\r\n");
      out.write("\t\t      joinMemberJUNE = resp[0][\"JUNE\"];\r\n");
      out.write("\t\t      joinMemberJULY = resp[0][\"JULY\"];\r\n");
      out.write("\t\t      joinMemberAUGUST = resp[0][\"AUGUST\"];\r\n");
      out.write("\t\t      joinMemberSEPTEMBER = resp[0][\"SEPTEMBER\"];\r\n");
      out.write("\t\t      joinMemberOCTOBER = resp[0][\"OCTOBER\"];\r\n");
      out.write("\t\t      joinMemberNOVEMBER = resp[0][\"NOVEMBER\"];\r\n");
      out.write("\t\t      joinMemberDECEMBER = resp[0][\"DECEMBER\"];\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  error: function (request, status, error) {\r\n");
      out.write("\t\t      console.log(\"code: \" + request.status)\r\n");
      out.write("\t\t      console.log(\"message: \" + request.responseText)\r\n");
      out.write("\t\t      console.log(\"error: \" + error);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("getMemCNT();\r\n");
      out.write("getSubMemCNT();\r\n");
      out.write("selectSubEndCloseComList();\r\n");
      out.write("joinCompanyMemberCNT();\r\n");
      out.write("selectSalesSUM();\r\n");
      out.write("selectSalesItemCNT();\r\n");
      out.write("selectMonthlySubscribeCNT();\r\n");
      out.write("selectMonthlyJoinMemberCNT();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery Core Js -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/libscripts.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Plugin Js-->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/apexcharts.bundle.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/adminIndex.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/dataTables.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery Page Js -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/template.js\"></script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
