/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2023-06-07 03:46:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1679567181629L));
    _jspx_dependants.put("jar:file:/E:/A_TeachingMaterial/05_JSP_Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourmine/WEB-INF/lib/spring-webmvc-5.3.6.jar!/META-INF/spring.tld", Long.valueOf(1618279800000L));
    _jspx_dependants.put("jar:file:/E:/A_TeachingMaterial/05_JSP_Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourmine/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.6.jar", Long.valueOf(1680657633229L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.card::-webkit-scrollbar {\r\n");
      out.write("\t  display: none; /* Chrome, Safari, and Opera */\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div id=\"mytask-layout\" class=\"theme-indigo\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- main body area -->\r\n");
      out.write("    <div class=\"main px-lg-4 px-md-4\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Body: Body -->\r\n");
      out.write("        <div class=\"body d-flex py-3\">\r\n");
      out.write("            <div class=\"container-xxl\">\r\n");
      out.write("                <div class=\"row clearfix g-3\">\r\n");
      out.write("                    <div class=\"col-xl-8 col-lg-12 col-md-12 flex-column\">\r\n");
      out.write("                        <div class=\"row g-3\">\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                    <div class=\"card-header py-3 d-flex justify-content-between bg-transparent border-bottom-0\">\r\n");
      out.write("                                        <h6 class=\"mb-0 fw-bold \">프로젝트 진행률</h6>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"ac-line-transparent\" id=\"projectProgress\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                    <div class=\"card-header py-3 d-flex justify-content-between bg-transparent border-bottom-0\">\r\n");
      out.write("                                        <h6 class=\"mb-0 fw-bold \">산출물</h6>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"row g-2 row-deck\">\r\n");
      out.write("                                            <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                                <div class=\"card\">\r\n");
      out.write("                                                    <div class=\"card-body \">\r\n");
      out.write("                                                        <i class=\"icofont-home fs-3\"></i>\r\n");
      out.write("                                                        <h6 class=\"mt-3 mb-0 fw-bold small-14\">전체</h6>\r\n");
      out.write("                                                        <span class=\"text-muted\">400</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                                <div class=\"card\">\r\n");
      out.write("                                                    <div class=\"card-body \">\r\n");
      out.write("                                                            <i class=\"icofont-files-stack fs-3\"></i>\r\n");
      out.write("                                                        <h6 class=\"mt-3 mb-0 fw-bold small-14\">일감</h6>\r\n");
      out.write("                                                        <span class=\"text-muted\">17</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                                <div class=\"card\">\r\n");
      out.write("                                                    <div class=\"card-body \">\r\n");
      out.write("                                                            <i class=\"icofont-ui-clip-board fs-3\"></i>\r\n");
      out.write("                                                        <h6 class=\"mt-3 mb-0 fw-bold small-14\">이슈</h6>\r\n");
      out.write("                                                        <span class=\"text-muted\">06</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                                <div class=\"card\">\r\n");
      out.write("                                                    <div class=\"card-body \">\r\n");
      out.write("                                                        <i class=\"icofont-ui-folder fs-3\"></i>\r\n");
      out.write("                                                        <h6 class=\"mt-3 mb-0 fw-bold small-14\">파일</h6>\r\n");
      out.write("                                                        <span class=\"text-muted\">14</span> \r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                    <div class=\"card-header py-3 d-flex justify-content-between bg-transparent border-bottom-0\">\r\n");
      out.write("                                        <h6 class=\"mb-0 fw-bold \">프로젝트 완성 비율</h6>\r\n");
      out.write("                                        <h4 class=\"mb-0 fw-bold \">423</h4>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"mt-3\" id=\"projectCompletionRate\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                    <div class=\"card-header py-3 d-flex justify-content-between bg-transparent border-bottom-0\">\r\n");
      out.write("                                        <h6 class=\"mb-0 fw-bold \">부서별 월간 진행률</h6>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div id=\"progressByDepartment\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-lg-12 col-md-12\">\r\n");
      out.write("                        <div class=\"row g-3 row-deck\">\r\n");
      out.write("                            <div class=\"col-md-6 col-lg-6 col-xl-12\">\r\n");
      out.write("                                <div class=\"card bg-primary\">\r\n");
      out.write("                                    <div class=\"card-body row\">\r\n");
      out.write("                                        <div class=\"col\">\r\n");
      out.write("                                            <span class=\"avatar lg bg-white rounded-circle text-center d-flex align-items-center justify-content-center\"><i class=\"icofont-institution fs-5\"></i></span>\r\n");
      out.write("                                            <h1 class=\"mt-3 mb-0 fw-bold text-white\">OURmine</h1>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col\">\r\n");
      out.write("                                            <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/interview.svg\" alt=\"interview\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 col-lg-6 col-xl-12  flex-column\">\r\n");
      out.write("                                <div class=\"card mb-3\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center flex-fill\">\r\n");
      out.write("                                            <span class=\"avatar lg light-success-bg rounded-circle text-center d-flex align-items-center justify-content-center\"><i class=\"icofont-users-alt-2 fs-5\"></i></span>\r\n");
      out.write("                                            <div class=\"d-flex flex-column ps-3  flex-fill\">\r\n");
      out.write("                                                <span class=\"text-muted\">직원</span>\r\n");
      out.write("                                                <h6 class=\"fw-bold mb-0 fs-4\">246</h6>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center flex-fill\">\r\n");
      out.write("                                            <span class=\"avatar lg light-success-bg rounded-circle text-center d-flex align-items-center justify-content-center\"><i class=\"icofont-handshake-deal fs-5\"></i></span>\r\n");
      out.write("                                            <div class=\"d-flex flex-column ps-3 flex-fill\">\r\n");
      out.write("                                                <span class=\"text-muted\">프리랜서</span>\r\n");
      out.write("                                                <h6 class=\"fw-bold mb-0 fs-4\">101</h6>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-12 col-lg-12 col-xl-12\">\r\n");
      out.write("                                <div class=\"card\" style=\"height: 610px; overflow-y: scroll;\">\r\n");
      out.write("\t                                <div class=\"card-body\">\r\n");
      out.write("\t                                    <div class=\"flex-grow-1\">\r\n");
      out.write("\t                                        <div class=\"py-3 d-flex align-items-center border-bottom flex-wrap\">\r\n");
      out.write("\t                                            <div class=\"d-flex align-items-center flex-fill\">\r\n");
      out.write("\t                                                <img class=\"avatar lg rounded-circle img-thumbnail\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("\t                                                <div class=\"d-flex flex-column ps-3\">\r\n");
      out.write("\t                                                    <h6 class=\"fw-bold mb-0 small-14\">정재환</h6>\r\n");
      out.write("\t                                                    <span class=\"text-muted\">wjdwoghks@naver.com</span>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                            <div class=\"time-block text-truncate\">\r\n");
      out.write("\t                                                <i class=\"icofont-id-card\"></i> MANAGER\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                        <div class=\"py-3 d-flex align-items-center border-bottom flex-wrap\">\r\n");
      out.write("\t                                            <div class=\"d-flex align-items-center flex-fill\">\r\n");
      out.write("\t                                                <img class=\"avatar lg rounded-circle img-thumbnail\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("\t                                                <div class=\"d-flex flex-column ps-3\">\r\n");
      out.write("\t                                                    <h6 class=\"fw-bold mb-0 small-14\">강지웅</h6>\r\n");
      out.write("\t                                                    <span class=\"text-muted\">rkdwldnd@naver.com</span>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                            <div class=\"time-block text-truncate\">\r\n");
      out.write("\t                                                <i class=\"icofont-id-card\"></i> MANAGER\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                        <div class=\"py-3 d-flex align-items-center border-bottom flex-wrap\">\r\n");
      out.write("\t                                            <div class=\"d-flex align-items-center flex-fill\">\r\n");
      out.write("\t                                                <img class=\"avatar lg rounded-circle img-thumbnail\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("\t                                                <div class=\"d-flex flex-column ps-3\">\r\n");
      out.write("\t                                                    <h6 class=\"fw-bold mb-0 small-14\">배성환</h6>\r\n");
      out.write("\t                                                    <span class=\"text-muted\">qotjdghks@naver.com</span>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                            <div class=\"time-block text-truncate\">\r\n");
      out.write("\t                                                <i class=\"icofont-id-card\"></i> MANAGER\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                        <div class=\"py-3 d-flex align-items-center border-bottom flex-wrap\">\r\n");
      out.write("\t                                            <div class=\"d-flex align-items-center flex-fill\">\r\n");
      out.write("\t                                                <img class=\"avatar lg rounded-circle img-thumbnail\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("\t                                                <div class=\"d-flex flex-column ps-3\">\r\n");
      out.write("\t                                                    <h6 class=\"fw-bold mb-0 small-14\">김지현</h6>\r\n");
      out.write("\t                                                    <span class=\"text-muted\">rlawlgus@naver.com</span>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                            <div class=\"time-block text-truncate\">\r\n");
      out.write("\t                                                <i class=\"icofont-id-card\"></i> MEMBER\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                        <div class=\"py-3 d-flex align-items-center border-bottom flex-wrap\">\r\n");
      out.write("\t                                            <div class=\"d-flex align-items-center flex-fill\">\r\n");
      out.write("\t                                                <img class=\"avatar lg rounded-circle img-thumbnail\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("\t                                                <div class=\"d-flex flex-column ps-3\">\r\n");
      out.write("\t                                                    <h6 class=\"fw-bold mb-0 small-14\">나재경</h6>\r\n");
      out.write("\t                                                    <span class=\"text-muted\">skworud@naver.com</span>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                            <div class=\"time-block text-truncate\">\r\n");
      out.write("\t                                                <i class=\"icofont-id-card\"></i> MEMBER\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                        <div class=\"py-3 d-flex align-items-center border-bottom flex-wrap\">\r\n");
      out.write("\t                                            <div class=\"d-flex align-items-center flex-fill\">\r\n");
      out.write("\t                                                <img class=\"avatar lg rounded-circle img-thumbnail\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("\t                                                <div class=\"d-flex flex-column ps-3\">\r\n");
      out.write("\t                                                    <h6 class=\"fw-bold mb-0 small-14\">이제인</h6>\r\n");
      out.write("\t                                                    <span class=\"text-muted\">dlwpdls@naver.com</span>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                            <div class=\"time-block text-truncate\">\r\n");
      out.write("\t                                                <i class=\"icofont-id-card\"></i> MEMBER\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                        <div class=\"py-3 d-flex align-items-center border-bottom flex-wrap\">\r\n");
      out.write("\t                                            <div class=\"d-flex align-items-center flex-fill\">\r\n");
      out.write("\t                                                <img class=\"avatar lg rounded-circle img-thumbnail\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("\t                                                <div class=\"d-flex flex-column ps-3\">\r\n");
      out.write("\t                                                    <h6 class=\"fw-bold mb-0 small-14\">박성룡</h6>\r\n");
      out.write("\t                                                    <span class=\"text-muted\">qkrtjdfyd@naver.com</span>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                            <div class=\"time-block text-truncate\">\r\n");
      out.write("\t                                                <i class=\"icofont-id-card\"></i> MEMBER\r\n");
      out.write("\t                                            </div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <div class=\"card light-danger-bg\">\r\n");
      out.write("                            <div class=\"card-header py-3 d-flex justify-content-between bg-transparent border-bottom-0\">\r\n");
      out.write("                                <h6 class=\"mb-0 fw-bold \">팀별 프로젝트 진행도</h6>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <div class=\"row g-3 align-items-center\">\r\n");
      out.write("                                    <div class=\"col-md-12 col-lg-12 col-xl-12 col-xxl-12\">\r\n");
      out.write("                                        <div class=\"row g-3 row-cols-2 row-cols-sm-3 row-cols-md-3 row-cols-lg-3 row-cols-xl-3 row-cols-xxl-6 row-deck top-perfomer\">\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"card shadow\">\r\n");
      out.write("                                                    <div class=\"card-body text-center d-flex flex-column justify-content-center\">\r\n");
      out.write("                                                        <img class=\"avatar lg rounded-circle img-thumbnail mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("                                                        <h6 class=\"fw-bold my-2 small-14\">PM 이름</h6>\r\n");
      out.write("                                                        <span class=\"text-muted mb-2\">@프로젝트명</span>\r\n");
      out.write("                                                        <h4 class=\"fw-bold text-primary fs-3\">80%</h4>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"card shadow\">\r\n");
      out.write("                                                    <div class=\"card-body text-center d-flex flex-column justify-content-center\">\r\n");
      out.write("                                                        <img class=\"avatar lg rounded-circle img-thumbnail mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("                                                        <h6 class=\"fw-bold my-2 small-14\">PM 이름</h6>\r\n");
      out.write("                                                        <span class=\"text-muted mb-2\">@프로젝트명</span>\r\n");
      out.write("                                                        <h4 class=\"fw-bold text-primary fs-3\">70%</h4>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"card shadow\">\r\n");
      out.write("                                                    <div class=\"card-body text-center d-flex flex-column justify-content-center\">\r\n");
      out.write("                                                        <img class=\"avatar lg rounded-circle img-thumbnail mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("                                                        <h6 class=\"fw-bold my-2 small-14\">PM 이름</h6>\r\n");
      out.write("                                                        <span class=\"text-muted mb-2\">@프로젝트명</span>\r\n");
      out.write("                                                        <h4 class=\"fw-bold text-primary fs-3\">77%</h4>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"card shadow\">\r\n");
      out.write("                                                    <div class=\"card-body text-center d-flex flex-column justify-content-center\">\r\n");
      out.write("                                                        <img class=\"avatar lg rounded-circle img-thumbnail mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("                                                        <h6 class=\"fw-bold my-2 small-14\">PM 이름</h6>\r\n");
      out.write("                                                        <span class=\"text-muted mb-2\">@프로젝트명</span>\r\n");
      out.write("                                                        <h4 class=\"fw-bold text-primary fs-3\">85%</h4>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"card shadow\">\r\n");
      out.write("                                                    <div class=\"card-body text-center d-flex flex-column justify-content-center\">\r\n");
      out.write("                                                        <img class=\"avatar lg rounded-circle img-thumbnail mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("                                                        <h6 class=\"fw-bold my-2 small-14\">PM 이름</h6>\r\n");
      out.write("                                                        <span class=\"text-muted mb-2\">@프로젝트명</span>\r\n");
      out.write("                                                        <h4 class=\"fw-bold text-primary fs-3\">95%</h4>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"card shadow\">\r\n");
      out.write("                                                    <div class=\"card-body text-center d-flex flex-column justify-content-center\">\r\n");
      out.write("                                                        <img class=\"avatar lg rounded-circle img-thumbnail mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xs/마스코트_투명.png\" alt=\"profile\">\r\n");
      out.write("                                                        <h6 class=\"fw-bold my-2 small-14\">PM 이름</h6>\r\n");
      out.write("                                                        <span class=\"text-muted mb-2\">@프로젝트명</span>\r\n");
      out.write("                                                        <h4 class=\"fw-bold text-primary fs-3\">97%</h4>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!-- Row End -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery Core Js -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Plugin Js-->\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/memIndex.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery Page Js -->\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
